# monitoring/promtail-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # 1) Untuk Docker - baca container logs
  - job_name: docker_containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "service"

  # 2) Untuk Windows Service - baca dari folder publish
  - job_name: windows_services
    static_configs:
      - targets:
          - localhost
        labels:
          job: "windows-services"
          environment: "production"
          __path__: /logs/publish/logs_*/*.txt # âœ… PATH DARI DALAM CONTAINER
